"""Change analysis field

Revision ID: 668ed23c301e
Revises: 03e4696b2904
Create Date: 2025-05-05 12:11:20.625273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '668ed23c301e'
down_revision = '03e4696b2904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dominant_emotion_label', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('dominant_emotion_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('emotion_details_json', sa.JSON(), nullable=True))
        batch_op.drop_index('ix_diary_entries_sentiment_label')
        batch_op.drop_index('ix_diary_entries_sentiment_score')
        batch_op.create_index(batch_op.f('ix_diary_entries_dominant_emotion_label'), ['dominant_emotion_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_diary_entries_dominant_emotion_score'), ['dominant_emotion_score'], unique=False)
        batch_op.drop_column('sentiment_score')
        batch_op.drop_column('sentiment_label')
        batch_op.drop_column('sentiment_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sentiment_label', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('sentiment_score', sa.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_diary_entries_dominant_emotion_score'))
        batch_op.drop_index(batch_op.f('ix_diary_entries_dominant_emotion_label'))
        batch_op.create_index('ix_diary_entries_sentiment_score', ['sentiment_score'], unique=False)
        batch_op.create_index('ix_diary_entries_sentiment_label', ['sentiment_label'], unique=False)
        batch_op.drop_column('emotion_details_json')
        batch_op.drop_column('dominant_emotion_score')
        batch_op.drop_column('dominant_emotion_label')

    # ### end Alembic commands ###
